subifinancial/subi-connect

- src/pages/payroll-integration-management/index.tsx
Fixed the visibility issue of the 'Add another organisation' button for small screens.
- Updated `src/pages/payroll-integration-management/index.tsx` to add a class that controls the visibility of the button text based on the screen size.
1. Navigate to the payroll integration management page.
2. Verify that the 'Add another organisation' button text is hidden on small screens and visible on larger screens.
The change ensures that the button text does not clutter the UI on small screens, improving readability and user experience.
> fix: improve mobile responsiveness

- .github/workflows/release.yml
Changed the node registry URL from GitHub to npm and updated authentication tokens in the release workflow configuration.
- Updated the registry-url from `https://npm.pkg.github.com` to `https://registry.npmjs.org` in the `actions/setup-node` step.
- Changed `GITHUB_TOKEN` to `NPM_TOKEN` and `NODE_AUTH_TOKEN` to use secrets `NPM_AUTH_TOKEN` instead of `GITHUB_TOKEN`.
1. Trigger a workflow dispatch for the release workflow.
2. Ensure the dependencies are installed correctly from npm registry.
3. Verify that the package is published successfully using the new `NPM_TOKEN`.
The change aims to switch to npm registry for easier distribution.
> chore: move to npm registry

- .github/workflows/release.yml
Added the missing `GITHUB_TOKEN` to the release workflow to ensure successful authentication during the deployment process.
> fix: add GITHUB_TOKEN to changesets action

- .github/workflows/release.yml
Add push trigger to release workflow for main branch.
- Added push trigger for the main branch in the release workflow.
- Updated the concurrency key in the workflow.
- Added conditional step to run the release job if the push event is on 'refs/heads/main' and the previous reference is 'refs/heads/changeset-release/main'.
> fix: add auto release on merge from changeset-release

- .changeset/clever-houses-call.md
Added `hasConnection` field to the useCompany to determine if the company has integrated with a payroll yet. This PR adds the Changeset.
> chore: add cs for previous pr

- .github/workflows/release.yml
Updated the GitHub Actions release workflow to trigger on merged cs pull requests.
- Modified `.github/workflows/release.yml` to change the trigger event to `pull_request` with a type of `closed` rather than to specific branches.
> fix: github workflow on cs merge

- .changeset/fluffy-papayas-build.md
- .github/workflows/release.yml
- rollup.config.mjs
Removed the creation of the `.env.production` file from the GitHub Actions release workflow, and updated the Rollup configuration to use environment-specific `.env` files based on the `NODE_ENV` variable.
- Removed the creation of `.env.production` file in `.github/workflows/release.yml`.
- Updated `rollup.config.mjs` to load environment-specific `.env` files based on `NODE_ENV`.
1. Trigger the GitHub Actions release workflow and ensure it skips the creation of `.env.production` file.
2. Verify that the build process works correctly and environment variables are loaded based on the `NODE_ENV` setting.
> fix: load normal envs during build

- .changeset/fuzzy-flies-raise.md
- .github/workflows/release.yml
Add correct URL envs to the release build in the GitHub Actions workflow.
- Added environment variables `SUBI_CONNECT_IMAGES_BASE_URL` and `SUBI_CONNECT_PUBLIC_BASE_URL` to the build step in `.github/workflows/release.yml`.
- Created a changeset file `.changeset/fuzzy-flies-raise.md` marking the change as a patch for `@subifinancial/subi-connect`.
Verify that the release build in the GitHub Actions workflow uses the correct URL environment variables.
> fix: add envs to release build

- package.json
The registry URL in the publishConfig section of package.json has been updated from GitHub's npm registry to the official npm registry.
- Updated the registry URL in `package.json` from `https://npm.pkg.github.com/subifinancial` to `https://registry.npmjs.org/`.
1. Verify the `registry` field under `publishConfig` in `package.json` is now `https://registry.npmjs.org/`.
2. Ensure package publishing points to the official npm registry.
This change standardizes the package publishing process by using the official npm registry, facilitating easier access and distribution of the package.
> fix: change publishConfig to npm registry

- .changeset/olive-shoes-teach.md
- src/pages/payroll-integration-management/index.tsx
Add a `disableBack` flag to the `PayrollIntegrationManagementPage` header component. This is used to remove the ability to 'go back' when using the component outside of the `PayrollIntegrationsPage` component.
> Add a `disableBack` flag to the `PayrollIntegrationManagementPage` header component

- README.md
- rollup.config.mjs
- scripts/pack.sh
- src/services/logger/local-logger.ts
- src/types/main.ts
Updated various scripts and configurations to use `TARGET_ENV` instead of `NODE_ENV` for the environment variable.
1. Updated `README.md` to reflect the change from `NODE_ENV` to `TARGET_ENV`.
2. Modified `rollup.config.mjs` to load `.env` based on `TARGET_ENV` instead of `NODE_ENV`.
3. Adjusted `scripts/pack.sh` to utilize `TARGET_ENV`.
4. Updated `local-logger.ts` to check `TARGET_ENV` for logging decisions.
5. Changed comments and types in `main.ts` documentation from `NODE_ENV` to `TARGET_ENV`.
1. Run `npm run build-storybook` and `npm run storybook` to ensure functioning as expected.
2. Verify that the appropriate `.env` files are being loaded based on `TARGET_ENV`.
3. Run the modified `pack.sh` script and ensure assets are built correctly.
4. Check logging behavior in local …
> refactor: change NODE_ENV to TARGET_ENV

- .changeset/clean-badgers-heal.md
- demo/world-pay/package-lock.json
- demo/world-pay/package.json
- src/components/payroll-integration/card/base-card.tsx
- src/components/payroll-integration/grid.tsx
- src/context/subi-connect.tsx
- src/hooks/index.ts
- src/index.ts
- src/lib/handle-provider-options.tsx
- src/services/logger/local-logger.ts
- src/types/index.ts
- src/types/main.ts
- src/types/utils.ts
This pull request aims to expose all types from the `@subifinancial/subi-connect` package.
- Exposed all types from the `@subifinancial/subi-connect` package
- Updated package-lock.json and package.json to reflect the new version of the package
- Made visual adjustments to some components to accommodate new types
- Enhanced the SubiConnect context to include an `initialised` state
- Updated hooks to export additional functionalities
1. Verify that all types are exported correctly from `@subifinancial/subi-connect`.
2. Check the visual adjustments in the relevant components.
3. Ensure that the context `initialised` state works as intended.
4. Validate the new hooks functionalities.
This change is necessary to provide full type support for the `@subifinancial/subi-connect` package.
> Expose all Subi Connect types

- src/services/logger/local-logger.ts
- src/types/main.ts
Changed environment variable references from `TARGET_ENV` to `NODE_ENV` in `LocalLogger` and main type definitions to standardize on the use of `NODE_ENV` for environment-specific logic.
Replaced all occurrences of `TARGET_ENV === 'local'` with `NODE_ENV === 'development'` in `LocalLogger` class and updated comments in main type definitions.
1. Set `NODE_ENV` to `development`.
2. Run the application and observe that logging is directed to the console.
3. Set `NODE_ENV` to `production`.
4. Run the application and confirm that logging is disabled.
To ensure consistent usage of the `NODE_ENV` environment variable for environment-specific conditions and to follow common Node.js practices.
> fix: move local logging to NODE_ENV config

- .changeset/nervous-laws-cross.md
- demo/world-pay/package-lock.json
- demo/world-pay/package.json
- package-lock.json
- src/hooks/index.ts
- src/hooks/use-company.tsx
- src/services/api/company/actions.ts
- src/services/api/company/paths.ts
Added a new hook `useCompanyPayrollIntegrations` to fetch company's connected payroll integrations.
- Introduced a new hook `useCompanyPayrollIntegrations` in `use-company.tsx`
- Added a new API action `getCompanyPayrollIntegrations` in `company/actions.ts`
- Created a new API path `COMPANY_PAYROLL_INTEGRATIONS_URL` in `company/paths.ts`
- Exported the new hook from `hooks/index.ts`
1. Import the `useCompanyPayrollIntegrations` hook in a component
2. Use the hook to fetch payroll integrations data
3. Verify that the hook returns the expected data structure (Payroll[] | null)
4. Check that the API call is made to the correct endpoint (/company/integrations)
This change allows developers to easily fetch and display the payroll integrations that a company has connected with. It enhances the …
> Add useCompanyPayrollIntegrations hook for company integrations

- .changeset/chatty-beers-sell.md
- src/components/employees-table/columns/company-specific.tsx
- src/components/payroll-integration-instructions/api-input.tsx
- src/components/payroll-integration-instructions/domain-input.stories.tsx
- src/components/payroll-integration-instructions/domain-input.tsx
- src/components/payroll-integration-instructions/inputs.stories.tsx
- src/index.css
- src/integration-pages/custom/index.tsx
- src/ui/data-table-toolbar.tsx
- src/ui/extended/table/columns/sync/sync-status.tsx
Updated input components to prevent auto-completion and improved form handling in stories.
- Modified ApiKeyInput and DomainInput components to disable auto-completion
- Updated stories for ApiKeyInput, DomainInput, and created a new combined Inputs story
- Adjusted form handling in stories to use React Hook Form and display submitted data
- Added CSS to hide auto-fill buttons in Safari
1. Run the Storybook and navigate to the Form Components section
2. Test the ApiKeyInput, DomainInput, and combined Inputs stories
3. Verify that auto-completion is disabled for both inputs
4. Submit the forms and check if the entered data is correctly displayed
5. Test in Safari to ensure auto-fill buttons are hidden
This change improves the user experience and security of the input components by …
> Disable autocomplete for API key and domain inputs

- .github/workflows/deploy.yml
Enhanced GitHub Actions workflow for deploying demos with improved visibility and naming.
- Added a `run-name` to the workflow, which now displays the target environment in the GitHub Actions UI.
- Updated the emoji for the "Deploy subi-connect demo" job from ✈️ to 🛫 for better visual distinction.
1. Trigger the workflow manually in GitHub Actions.
2. Verify that the new run name appears in the Actions tab, showing the target environment.
3. Check that the "Deploy subi-connect demo" job now displays the 🛫 emoji instead of ✈️.
These updates improve the workflow's visibility and readability in the GitHub Actions UI. The dynamic run name provides immediate context about the deployment target, while the updated emoji offers better visual differentiation for the specific deployment job.
> chore: add env to deploy demos script

- .github/workflows/deploy-all-demos.yml
- .github/workflows/deploy.yml
Added a new workflow for deploying demos to all environments and updated the existing deploy workflow to support reusability.
- Created a new workflow file `deploy-all-demos.yml` that triggers deployments to all environments (dev, stg, prod) on workflow dispatch or when a new tag is pushed.
- Modified the existing `deploy.yml` workflow to support being called by other workflows.
- Updated the `deploy.yml` workflow to use `inputs.env` instead of `github.event.inputs.env` for broader compatibility.
- Adjusted the concurrency group in `deploy.yml` to use the new input format.
1. Manually trigger the new "Deploy Demos to All Environments" workflow from the Actions tab.
2. Push a new tag (e.g., `v1.0.0`) to trigger automatic deployment to all environments.
3. Verify that the existing manual …
> chore: update workflows to deploy all demos on version bump

- .github/workflows/deploy.yml
Updated GitHub Actions workflow to use `inputs.env` instead of `github.event.inputs.env` and modified artifact naming.
- Replaced `${{ github.event.inputs.env }}` with `${{ inputs.env }}` throughout the workflow file.
- Updated the artifact name for the subi-connect library to include the environment: `subiconnect-lib-${{ inputs.env }}`.
- Adjusted the download artifact step in the build-demo job to use the new artifact name.
1. Trigger the workflow manually with different environment inputs.
2. Verify that the correct environment is used throughout the workflow.
3. Check that the artifacts are correctly named and downloaded in subsequent jobs.
4. Ensure the demo builds and deploys successfully for each environment.
This change improves the workflow's flexibility and clarity by:
1. …
> chore (workflows): update deployment build artifact name to include env

- .github/workflows/deploy.yml
Updated artifact naming in GitHub Actions workflow to include environment.
- Modified the artifact name in the "Save Build as Artifact" step to include the environment variable: `subiconnect-demo-${{ inputs.env }}`
- Updated the corresponding artifact name in the "Download Build Artifacts" step to match the new naming convention
1. Trigger the GitHub Actions workflow for different environments
2. Verify that the artifact names include the environment identifier
3. Ensure the "Download Build Artifacts" step successfully retrieves the correctly named artifact
This change allows for better differentiation between artifacts from different environments, improving clarity and reducing the risk of deploying the wrong build to a specific environment.
> chore (workflows): update demo deployement build artifact to include env

- .github/workflows/pull_request.yml
- src/components/payroll-integration-instructions/domain-input.tsx
Updated GitHub Actions workflow and improved domain input component styling.
- Renamed the lint job in the GitHub Actions workflow to "🧼 Lint"
- Modified the styling of the domain input component:
- Changed the overflow property from `clip` to `visible` for the main container
- Updated the styling for the subdomain display, improving responsiveness and scroll behaviour
1. Review the GitHub Actions workflow to ensure the lint job is correctly named
2. Test the domain input component on various screen sizes:
- Verify that the subdomain display is visible and scrollable on smaller screens
- Confirm that the subdomain display is properly positioned on larger screens
3. Check that the overflow behaviour of the domain input component is correct
- The workflow rename provides a clearer …
> fix: domain input ui/ux

- .changeset/unlucky-needles-sin.md
- src/components/payroll-integration-instructions/components-map.tsx
- src/components/payroll-integration-instructions/custom-link.tsx
- src/index.css
Added a CustomLink component and updated the components map and CSS styles.
- Created a new `CustomLink` component in `custom-link.tsx`
- Added `CustomLink` to the `otherComponentsMap` in `components-map.tsx`
- Modified the CSS in `index.css` to apply the font-family directly to the `.subi-connect` class instead of all its children
1. Verify that the `CustomLink` component renders correctly when used in the payroll integration instructions.
2. Check that links open in a new tab with the appropriate `rel` attribute.
3. Ensure that the font-family is applied correctly to the `.subi-connect` class and its children.
The `CustomLink` component was added to provide a consistent and secure way to render external links within the payroll integration instructions. This ensures that all links open …
> fix: add CustomLink to alter the default behaviour of 'a' tags in integration instructions

- .github/workflows/deploy-all-demos.yml
Updated the trigger for the "Deploy Demos to All Environments" workflow.
Modified the workflow trigger from push events on tags starting with 'v' to release events of type 'published'.
1. Create a new release in the repository.
2. Publish the release.
3. Verify that the "Deploy Demos to All Environments" workflow is triggered automatically.
This change ensures that the deployment workflow is triggered only when a release is published, rather than on every tag push. This provides more control over when deployments occur and aligns the process with the release lifecycle.
> chore (workflows): update deploy all demos workflow to run on package release

- .changeset/wicked-shoes-compete.md
- src/components/connect-and-integrate/index.tsx
Increased the maximum width of the dialogue content for larger screens.
Modified the `className` prop of the `DialogueContent` component in the `Integrate` component. Specifically, the `md:sc-max-w-2xl` class was changed to `md:sc-max-w-4xl`, increasing the maximum width for medium and larger screens.
1. Navigate to the page containing the Connect and Integrate component.
2. Trigger the dialogue to open.
3. Resize the browser window to a medium or larger screen size.
4. Verify that the dialogue content expands to a wider maximum width compared to before.
This change was likely made to improve the user experience on larger screens by allowing more content to be displayed horizontally. The increased width can potentially reduce vertical scrolling and make better use of available screen …
> fix: update integration dialogue instructions max width

- .changeset/silly-penguins-love.md
- src/components/payroll-integration/grid.tsx
- src/pages/employee-management/index.tsx
- src/pages/payroll-integration-management/index.tsx
- src/pages/payroll-integrations/index.tsx
- src/stories/wrapper.tsx
- src/ui/data-table.tsx
Removed 'subi-connect' class from components inside the provider div container.
- The 'subi-connect' class has been removed from various components and pages.
- It is now only applied to the provider div container in '@src/context/subi-connect.tsx' and the dialogue component in '@src/ui/dialogue.tsx'.
- Updated class names in multiple files to remove the 'subi-connect' class.
1. Check the rendered HTML of affected components to ensure the 'subi-connect' class is not present.
2. Verify that the provider div container and dialogue component still have the 'subi-connect' class.
3. Ensure that the styling and layout of the components remain intact after the class removal.
This change aims to improve the specificity of the 'subi-connect' class usage. By limiting its application to only the …
> fix: remove subi-connect class from components inside provider div container

- .github/workflows/deploy-all-demos.yml
Updated the trigger for the "Deploy Demos to All Environments" workflow.
Modified the release event type that triggers the workflow from "published" to "created".
1. Create a new release in the repository.
2. Verify that the "Deploy Demos to All Environments" workflow is triggered automatically.
3. Ensure that the workflow runs successfully and deploys the demos as expected.
This change allows the deployment process to start earlier in the release cycle. By triggering the workflow when a release is created rather than when it's published, we can potentially catch and address any deployment issues sooner, improving the overall release process efficiency.
> chore (workflows): change deploy-all-demos trigger to a created release (from published)

- .changeset/fair-apples-remember.md
- src/components/connect-and-integrate/index.tsx
- src/components/payroll-integration/card/base-card.tsx
- src/components/payroll-integration/card/variants/coming-soon.tsx
- src/components/payroll-integration/card/variants/connect.tsx
- src/components/payroll-integration/card/variants/connected.tsx
- src/lib/utils.ts
- src/pages/payroll-integration-management/index.tsx
- src/types/application.ts
Introduced a new `getPayrollFriendlyName` function to display user-friendly payroll system names throughout the application.
- Added a `getPayrollFriendlyName` utility function in `src/lib/utils.ts`
- Updated various components to use the new function for displaying payroll system names
- Added a `friendlyName` property to the `AccountPayrollSystemExtended` type
- Replaced direct references to `payrollSystem.name` with `getPayrollFriendlyName(payrollSystem)`
1. Navigate to the payroll integration management page
2. Verify that payroll system names are displayed correctly, using friendly names where available
3. Check the connect, coming soon, and connected card variants to ensure they display the correct payroll system names
4. Test the integration workflow to confirm the dialogue title …
> feat: add friendlyName to the account payroll system

- .github/workflows/deploy-all-demos.yml
Updated the trigger for the "Deploy Demos to All Environments" workflow.
The workflow trigger has been modified from responding to release creation events to now triggering on push events for version tags. Specifically:
- Removed the `release` trigger and its `types: [created]` condition
- Added a `push` trigger with `tags: ['v*.*.*']` condition
1. Create and push a new version tag (e.g., `v1.0.0`) to the repository
2. Verify that the "Deploy Demos to All Environments" workflow is triggered automatically
3. Ensure that creating a new release without pushing a tag does not trigger the workflow
This change allows for more precise control over when the deployment workflow runs. By triggering on version tags instead of release creation, it ensures that deployments are tied directly to …
> chore (workflows): update deploy all demos to run on version changes

- src/services/axios/connection-service.ts
This PR modifies the `ConnectionService` class to use hexadecimal encoding and decoding for the context instead of base64. It introduces two new private methods, `hexEncodeContext` and `hexDecodeContext`, to handle the conversion between plain text and hexadecimal representation.
The change from base64 to hexadecimal encoding provides a more consistent and reliable way to handle the context data, especially when dealing with binary data or special characters. This approach reduces the likelihood of encoding-related issues and improves overall data integrity.
> fix: move from atob to hex encode

- .changeset/few-boats-share.md
- src/context/subi-connect.tsx
- src/hooks/internal/use-query-params.ts
- src/hooks/use-account-payroll.tsx
- src/hooks/use-company.tsx
- src/hooks/use-connected-payrolls.tsx
- src/hooks/use-employees.tsx
- src/hooks/use-organisations.tsx
- src/hooks/use-payroll-systems.tsx
- src/hooks/use-subi-connect-query.ts
- src/integration-pages/custom/mutation.tsx
This PR introduces a wrapper for queries and mutations in Subi Connect to ensure they are used within the correct context. It also updates various hooks to use this new wrapper.
This change enhances error handling by throwing a specific error when Subi Connect hooks are used outside of the SubiConnectProvider context. It improves the developer experience by providing clearer error messages and enforcing proper usage of the Subi Connect library.
> fix: add error boundary for hooks

- .changeset/neat-cobras-yawn.md
- src/services/axios/connection-service.ts
This PR removes the dependency on the Buffer module by implementing custom hexadecimal encoding and decoding functions for the context string.
The change eliminates the reliance on the Node.js-specific Buffer module, potentially improving compatibility with browser environments and reducing the overall package size.
> fix: remove Buffer dependency

- .changeset/two-socks-float.md
- .github/workflows/deploy-all-demos.yml
- README.md
- demo/world-pay/package-lock.json
- demo/world-pay/src/components/extended/code-block.tsx
- demo/world-pay/src/context/subi-connect-wrapper.tsx
- src/components/payroll-integration/live.stories.tsx
- src/constants.ts
- src/context/subi-connect.tsx
- src/services/axios/connection-service.ts
- src/services/axios/utils/get-token.ts
- src/stories/wrapper.tsx
- src/types/main.ts
This PR introduces a major version change to the `@subifinancial/subi-connect` package, focusing on improving the handling of company context and enhancing type safety.
The changes address the need for a more robust and type-safe way to handle company-specific contexts in the SubiConnect provider. It also simplifies the API by removing redundant options and improving the overall structure of the connection service.
1. `SubiConnectProvider` now requires a `companyContext` prop.
2. Removed the `context` option from `SubiConnectOptions`.
1. Added type safety for the `companyContext` prop in `SubiConnectProvider`.
1. Updated `ACCESS_TOKEN_NAME` constant to use a shorter name: 'sc-cat'.
2. Enhanced `ConnectionService` to handle context changes and update stored access tokens.
3. Improved type …
> feat: add companyContext prop to SubiConnectProvider

- .changeset/grumpy-nails-end.md
- src/services/axios/connection-service.ts
This PR fixes an issue with the `setContext` method in the `ConnectionService` class. It now properly encodes the context during the access token context update process.
The previous implementation was not encoding the context when updating the access token context, which could lead to inconsistencies in context handling. This change ensures that the context is properly encoded before being used in the access token update.
> fix: encode context during access token context update

- demo/world-pay/package-lock.json
- demo/world-pay/vite.config.ts
This PR updates the `subi-connect` package to version 3.1.0 and enhances the Vite configuration to support HTTPS in development mode when environment variables for SSL certificates are provided.
The update to `subi-connect` brings in the latest features and improvements. Additionally, the Vite configuration changes allow developers to run the application with HTTPS locally, which can be necessary for testing certain features or integrations that require secure connections.
> chore (demos): add https to localhost

- .changeset/hip-garlics-tie.md
- demo/world-pay/package-lock.json
- demo/world-pay/package.json
- demo/world-pay/vite.config.ts
- src/components/employees-table/columns/additional-fields/calendar/next-payment-date.tsx
- src/components/employees-table/columns/additional-fields/calendar/paycycle.tsx
- src/components/employees-table/columns/additional-fields/calendar/start-employment-date.tsx
- src/components/employees-table/columns/additional-fields/hourly-rate.tsx
- src/components/employees-table/columns/additional-fields/salary.tsx
- src/components/employees-table/columns/core.tsx
- src/components/employees-table/consts.ts
- src/components/employees-table/index.tsx
- src/context/table/columns/calendars/calendar-context.tsx
- src/context/table/columns/salaries/salary-context.tsx
- src/pages/employee-management/live.stories.tsx
- src/services/api/employee/types.ts
- src/types/employee.ts
- src/ui/data-table.tsx
This pull request updates the employee table component to support multiple salaries and calendars per employee. It introduces new context providers for managing salary and calendar selections, and modifies the table columns to display selectable options when an employee has multiple salaries or calendars.
The existing implementation only supported a single salary and calendar per employee. This change allows for more flexible employee data representation, accommodating scenarios where employees may have multiple salaries or calendars associated with their profile.
> feat: support multiple salaries and calendars for employees

- .changeset/light-pants-applaud.md
- src/components/employees-table/index.tsx
This change modifies the `EmployeesTable` component to return `undefined` when the `contexts` array is empty, instead of returning an empty array.
The modification ensures that when no contexts are enabled, the component returns `undefined` rather than an empty array. This can potentially optimize performance and improve consistency in how the absence of contexts is represented.
> fix: Employee table with no added columns

- .changeset/clean-rice-think.md
- src/context/subi-connect.tsx
- src/hooks/use-subi-connect-query.ts
This PR updates the `SubiConnectProvider` and `useSubiConnectQuery` components to improve dependency management and query execution control.
The changes address potential issues with stale closures and ensure that queries are only executed when the SubiConnect context is properly initialized.
In the `SubiConnectProvider`:
- Added `companyContext` to the dependency array of the `logger` useMemo hook.
- Added `companyContext` to the dependency array of the `useEffect` hook that initializes the connection.
In the `useSubiConnectQuery` hook:
- Modified the hook to only enable queries when the SubiConnect context is initialized.
- Destructured the `enabled` option from the query options to combine it with the `initialised` state from the context.
These changes ensure proper reactivity to …
> fix: reinitiate when company context changes

- .changeset/heavy-points-brush.md
- src/services/axios/connection-service.ts
- src/services/axios/interceptors/error.ts
This PR introduces a new `updateAccessToken` method in the `ConnectionService` class. It also refactors the error interceptor to use this new method for updating the access token.
The change improves the token update process by encapsulating the logic within the `ConnectionService`. This ensures consistency in how the access token is updated across the application and simplifies the error interceptor's code.
> feat: add updateAccessToken method and refactor error interceptor

- .changeset/warm-rats-jog.md
- src/components/payroll-integration/card/variants/manual-connect.tsx
- src/components/payroll-integration/grid.tsx
- src/services/api/payroll/types.ts
This PR updates the handling of manual payroll connections and refines the display of payroll integration options. It introduces a new prop to control the visibility of manual connection types and updates the enum for payroll connection types.
The changes provide more flexibility in displaying payroll integration options, allowing for better control over which connection types are shown to users. It also ensures consistency in how manual payroll systems are referenced throughout the application.
> refactor: update manual payroll system handling

- .github/workflows/release.yml
This change modifies the release workflow to allow manual triggering of releases through workflow dispatch. It adds a condition to check if the `release` input is set to true when the workflow is manually dispatched.
The current workflow only allows releases to be triggered automatically when a pull request from the changeset release branch is merged. This update provides more flexibility by enabling manual release initiation when needed.
> ci: add manual release trigger option

- .changeset/spotty-hats-own.md
- src/context/subi-connect.tsx
Removes unnecessary dependencies (`connectionFn` and `companyContext`) from the `useEffect` dependency array in the `SubiConnectProvider` component.
The dependency array included variables that weren't actually being used within the effect, which could lead to unnecessary re-renders and potential performance issues.
> fix: remove unnecessary useEffect dependencies

- .changeset/afraid-walls-double.md
- src/context/subi-connect.tsx
Enhances the initialization process of the `SubiConnect` provider by optimizing state management and preventing unnecessary rerenders. The `cleanup` function is now memoized using `useCallback`, and state updates during initialization have been streamlined.
Addresses performance inefficiencies in the provider's initialization flow by:
- Setting the `initialised` state immediately when loading begins
- Eliminating redundant state checks and updates
- Preventing unnecessary rerenders through proper function memoization
- Ensuring proper dependency tracking in the value memo
> refactor: optimize SubiConnect provider initialization

- .changeset/shy-actors-peel.md
- src/context/subi-connect.tsx
- src/lib/handle-provider-options.tsx
- src/services/axios/connection-service.ts
Enhances the initialization process in SubiConnect by refactoring state management and provider configuration handling. The changes move provider options handling into the ConnectionService constructor and improve state tracking using useRef instead of useState.
Addresses inefficiencies in the initialization flow and state management by:
- Preventing unnecessary re-renders with useRef for initialization state
- Streamlining provider options configuration
- Improving the separation of concerns by moving provider options handling to ConnectionService
- Fixing dependency array issues in SubiConnectProvider's useMemo hook
> refactor: optimize SubiConnect initialization flow

- .changeset/rotten-donkeys-cross.md
- src/hooks/use-account-payroll.tsx
- src/hooks/use-employees.tsx
- src/hooks/use-organisations.tsx
- src/hooks/use-payroll-systems.tsx
Added `connectionService` context to dependency arrays in React hooks to ensure proper cache invalidation when the connection context changes. This update affects `useAccountPayrollSystem`, `useEmployees`, `useOrganisations`, `useAllOrganisations`, `useOrganisation`, and `usePayrollSystems` hooks.
The hooks were not properly invalidating their caches when the connection context changed, potentially leading to stale data being displayed. By adding the connection context to the dependency arrays, we ensure that the cached data is refreshed whenever the connection state changes.
> fix: add connectionService to hook dependency arrays

- .changeset/strange-eyes-behave.md
- src/components/employees-table/index.tsx
- src/components/payroll-integration-management-table/index.tsx
- src/context/table/table-context.tsx
- src/hooks/use-organisations.tsx
- src/pages/payroll-integration-management/index.tsx
- src/services/api/payroll/actions.ts
- src/services/api/payroll/paths.ts
- src/ui/extended/table/generic-table.tsx
This PR introduces two significant structural changes to improve consistency and clarity in the codebase:
1. Converts query key filters from array to object structure in table components
2. Renames `accountPayrollId` to `payrollSystemId` across payroll integration components
1. The array structure for query key filters was less intuitive and made type checking more difficult. The new object structure provides better type safety and clearer data organization.
2. The parameter naming inconsistency between `accountPayrollId` and `payrollSystemId` was causing confusion. The standardization to `payrollSystemId` better reflects its actual purpose.
> refactor: update query filters and payroll system ID structure
