subifinancial/subi-connect

.github/workflows/release.yml, demo/README.md, demo/world-pay/app/sc-override.css, demo/world-pay/package-lock.json, demo/world-pay/package.json, rollup.config.mjs, src/components/payroll-integration/card/variants/connected.tsx, src/components/payroll-integration/grid.tsx, src/components/payroll-integration/live.stories.tsx, src/context/table/pagination-context.tsx, src/context/table/search-context.tsx, src/context/table/table-context.tsx, src/hooks/internal/use-serach-params.ts, src/hooks/use-account-payroll.tsx, src/hooks/use-payroll-systems.tsx, src/pages/payroll-integration-management/index.stories.tsx, src/pages/payroll-integration-management/index.tsx, src/pages/payroll-integration-management/live.stories.tsx, src/pages/payroll-integrations/index.tsx, src/services/api/payroll/actions.ts, src/services/api/payroll/paths.ts, src/services/axios/config.ts, src/stories/mock-data/payroll.ts, src/types/query.ts
Change the flow to allow for multiple connections
=> feat: multi connections & improvements

demo/world-pay/.gitignore, demo/world-pay/app/backend/page.tsx, demo/world-pay/app/employees/page.tsx, demo/world-pay/app/integrations/custom/page.tsx, demo/world-pay/app/integrations/page.tsx, demo/world-pay/app/layout.tsx, demo/world-pay/app/main.tsx, demo/world-pay/app/nav-item.tsx, demo/world-pay/app/page.tsx, demo/world-pay/app/sc-override.css, demo/world-pay/app/search.tsx, demo/world-pay/components/extended/code-block.tsx, demo/world-pay/components/extended/lift-switch.tsx, demo/world-pay/components/extended/window.tsx, demo/world-pay/components/icons.tsx, demo/world-pay/components/lifted.tsx, demo/world-pay/components/protected-route.tsx, demo/world-pay/components/ui/label.tsx, demo/world-pay/components/ui/switch.tsx, demo/world-pay/context/authentication.tsx, demo/world-pay/context/lift-mode.tsx, demo/world-pay/context/subi-connect-wrapper.tsx, demo/world-pay/lib/connection-fn.tsx, demo/world-pay/package-lock.json, demo/world-pay/package.json, demo/world-pay/pnpm-lock.yaml, demo/world-pay/services/api/authentication/actions.ts, demo/world-pay/tsconfig.json, demo/world-pay/types/user.ts, src/pages/payroll-integrations/index.tsx
Updates the World Pay demo so it can be used without needing to edit the code.
- interactive api example and input
- 'lift mode' to easily see the Subi Connect components
=> [demo/worldpay] feat: add interactive api key input

src/components/payroll-integration/card/base-card.tsx, src/components/payroll-integration/card/variants/connected.tsx, src/components/payroll-integration/grid.tsx, src/hooks/internal/use-serach-params.ts
Alter the event name to avoid external clashes
=> Update layout and UI

package-lock.json, package.json, rollup.config.mjs, src/context/subi-connect.tsx, src/hooks/internal/use-query-params.ts, src/pages/payroll-integration-management/index.tsx, src/pages/payroll-integrations/index.tsx
=> feat: add 'use client' directives

README.md
=> fix: README links

README.md
=> fix: README links (#55)

.changeset/config.json, package.json
Change the base branch from 'dev' to 'main' in changeset configuration and update related scripts in package.json
=> fix: move changesets back to main

.changeset/config.json, package.json
Changed `.changeset/config.json` to set `access` to `public`, and updated various npm scripts in `package.json` to remove `--public` from `changeset publish` commands and fix repository URL format.
=> fix: package settings

.changeset/young-rules-relate.md
Added a changeset for the change regarding the tooltip to the sync status column headers to better understand what each status means.
Added tooltips to the sync status column headers.
Check the sync status column headers for the presence and accuracy of tooltips.
=> cs (patch): sync status tooltip

package.json
Added a description to the package.json for the @subifinancial/subi-connect package to provide more context about its purpose and usage.
=> fix: add description to package for npm

.changeset/great-files-add.md, src/context/subi-connect.tsx, src/lib/handle-provider-options.tsx, src/lib/utils.ts, src/services/axios/interceptors/error.ts, src/services/axios/interceptors/request.ts, src/services/axios/interceptors/response.ts, src/services/axios/utils/get-token.ts, src/services/logger/ILogger.ts, src/services/logger/index.ts, src/services/logger/local-logger.ts, src/types/main.ts
Updated the logger and added debugging options to the SubiConnectProvider. The update includes:
1. Replacing `logOnDev` with a more robust and flexible logging system.
2. Introducing `SubiConnectOptions` for debugging options in the `SubiConnectProvider` component.
3. Ensuring that logging can be enabled or disabled based on the environment.
4. Handling and logging errors appropriately using the new logger.
5. Allowing customization of the base URL for the API through the debug options.
=> feat: updated logger and added debug options

src/services/axios/utils/get-token.ts, src/services/logger/local-logger.ts, src/types/company.ts
Updated logger to provide more detailed and structured logging options for local development and error tracking. Added new optional `hasConnection` field to `Company` type.
- Improved the logging structure in `LocalLogger` for better readability and debugging.
- Updated `getAccessToken` to refine error logging.
- Extended `Company` type by including `hasConnection` field.
- Run the application in a local environment and verify the appearance of log messages.
- Confirm error logs are correctly formatted with additional error information.
- Validate that the `hasConnection` field can be used without any issues in the `Company` type.
These changes improve the developer experience by making logs clearer and more informative. The additional `hasConnection` field in the `Company` type aids in …
=> feat: added hasConnection field to company and improved logger

.changeset/sour-kangaroos-clean.md, .github/workflows/deploy.yml, .github/workflows/release.yml, package-lock.json, src/context/subi-connect.tsx, src/types/main.ts
=> feature(provider): add support to sandbox at runtime

.changeset/four-insects-run.md, src/components/payroll-integration/grid.tsx
=> fix(payroll: set payrollSystems as an empty array as default

.changeset/tricky-baboons-yell.md, src/context/subi-connect.tsx
=> fix(provider): remove sandbox baseURL

.changeset/large-geckos-matter.md, src/components/connect-and-integrate/index.tsx, src/components/payroll-integration-instructions/api-input.stories.tsx, src/components/payroll-integration-instructions/api-input.tsx, src/components/payroll-integration-instructions/components-map.tsx, src/components/payroll-integration-instructions/domain-input.stories.tsx, src/components/payroll-integration-instructions/domain-input.tsx, src/context/subi-connect.tsx, src/integration-pages/custom/index.tsx, src/mdx/render-mdx.tsx, src/ui/dialogue.tsx, src/ui/extended/table/columns/sync/types.ts, tailwind.config.js
Updated MDX form components UI/UX and improved internal typing.
- Enhanced the API Key Input component with masking functionality
- Improved the Domain Input component with subdomain extraction and visual feedback
- Added accessibility improvements to the Connect and Integrate dialogue
- Updated type definitions for better type safety
- Added Storybook stories for API Key Input and Domain Input components
- Implemented a wrapper div with 'subi-connect' class for better scoping
1. Test the API Key Input component:
- Enter an API key and verify that it's masked by default
- Hover over the input to reveal the actual characters
- Ensure the masking works correctly on mouse enter/leave events
2. Test the Domain Input component:
- Enter a domain and verify that it correctly extracts the …
=> cs: add changeset

.changeset/forty-pillows-drop.md, src/components/connect-and-integrate/index.tsx, src/components/payroll-integration/payroll-integration-list.tsx, src/context/payroll-integration.tsx, src/pages/payroll-integration-management/index.tsx
This pull request adds an `onIntegrationSuccess` callback to the payroll integration process. This new feature allows listening for when a payroll system has been successfully integrated.
It provides a way for developers to execute custom logic or perform additional actions when a payroll system integration is successful. This enhancement improves the flexibility and extensibility of the payroll integration workflow.
=> feat: add onIntegrationSuccess callback

package.json, src/components/payroll-integration/card/base-card.tsx, src/components/payroll-integration/get-error.tsx, src/components/payroll-integration/live.stories.tsx, src/components/payroll-integration/loading.tsx, src/components/payroll-integration/payroll-integration-list.tsx, src/pages/payroll-integration-management/index.tsx, src/ui/data-table-faceted-filter.tsx
This PR enhances the PayrollIntegrationList component and its related files. It adds a new local Storybook script, improves error handling, updates UI elements, and refines the responsive design of the payroll integration management page.
These changes address several issues:
1. Improves error handling and display in the PayrollIntegrationList component
2. Enhances the UI by updating icons and adjusting card styling
3. Improves responsiveness of the payroll integration management page
4. Adds a new Storybook script for local development
=> refactor: ui/ux improvements

demo/world-pay/package-lock.json, demo/world-pay/src/layout/index.tsx, src/components/connect-and-integrate/index.tsx, src/components/payroll-integration/card/variants/connect.tsx, src/components/payroll-integration/grid.tsx, src/context/subi-connect.tsx, src/context/table/table-context.tsx, src/hooks/use-account-payroll.tsx, src/hooks/use-company.tsx, src/hooks/use-connected-payrolls.tsx, src/hooks/use-employees.tsx, src/hooks/use-organisations.tsx, src/hooks/use-payroll-systems.tsx, src/pages/payroll-integration-management/index.tsx, src/types/main.ts, src/ui/data-table-faceted-filter.tsx
This PR updates the query key structure across multiple components and hooks to include the `SUBI_CONNECT_QUERY_KEY` and the connection context. It also refactors the base query keys for various entities to be more consistent.
The changes improve the organization and consistency of query keys throughout the application. By including the `SUBI_CONNECT_QUERY_KEY` and connection context in the query keys, it ensures proper isolation and management of queries across different connection contexts.
=> fix: query keys with context

demo/world-pay/package-lock.json, demo/world-pay/src/layout/index.tsx
This pull request updates the layout of the navigation menu in the World Pay demo application. It adds a divider between menu items, adjusts the positioning of the company selector, and updates dependencies in the package-lock.json file.
The changes improve the visual organization of the navigation menu, making it easier for users to distinguish between different sections. The repositioning of the company selector enhances the overall user experience by providing a more intuitive layout.
=> fix (demos): update worldpay layout

demo/world-pay/package-lock.json, package-lock.json
=> chore: update package-lock.json

.github/workflows/deploy-all-demos.yml, .github/workflows/release.yml
This PR updates the GitHub Actions workflows to include necessary permissions for deployment. It modifies the `deploy-all-demos.yml` and `release.yml` files to add `id-token: write` and `contents: read` permissions.
The changes address potential permission issues during the deployment process. By explicitly defining the required permissions, we ensure that the workflows have the necessary access to perform their tasks, particularly for actions that involve authentication or accessing repository contents.
=> chore (workflows): fix deploy demos

.changeset/nervous-laws-fix.md, src/components/connect-and-integrate/index.tsx, src/services/auth2.0/auth-window.ts, src/services/auth2.0/utils.ts, src/services/axios/index.ts
This PR refactors the OAuth2 authentication flow and improves the handling of authentication windows. It introduces a new utility function for generating auth window options and updates the connect and integrate component to use this new approach.
The changes aim to enhance the reliability and consistency of the OAuth2 authentication process, particularly in handling authentication windows across different scenarios. It also improves code reusability by extracting common logic into a separate utility function.
=> fix: auth window performance

demo/world-pay/package-lock.json, src/components/employees-table/columns/core.tsx, src/stories/mock-data/employee.ts
This PR enhances the email column in the employees table, and modifies the employee mock data structure to support multiple emails and salaries.
The changes improve the display and functionality of employee information, particularly for handling multiple email addresses and salary entries. The email column now shows the number of emails an employee has, and the mock data structure has been updated to reflect these changes.
=> fix: styling and examples

src/lib/utils.ts, src/services/api/payroll/actions.ts, src/services/api/payroll/paths.ts, src/services/api/payroll/types.ts, src/types/application.ts, src/types/payroll.ts, src/ui/button.tsx, tailwind.config.ts
This PR introduces several enhancements and updates to the codebase:
1. Adds a new `tw` utility function for template literal-based Tailwind class composition.
2. Implements support for manual payroll integration.
3. Refactors button variants to use the new `tw` function.
4. Updates the Tailwind configuration to TypeScript.
5. Enhances type definitions for payroll systems and applications.
These changes aim to improve code maintainability, extend payroll integration options, and enhance type safety throughout the project. The introduction of manual payroll integration provides more flexibility for users, while the refactoring of button variants and Tailwind configuration improves code consistency and type checking.
=> refactor: update types for manual integrations

.changeset/nine-trains-exercise.md, package-lock.json, src/components/connect-and-integrate/index.tsx, src/services/auth2.0/auth-window.ts, src/services/auth2.0/utils.ts
This PR updates the OAuth2 authentication flow in the Subi Connect package. It introduces a new check for OAuth status after the authentication window closes and improves the handling of window closure events.
The changes address potential issues with the OAuth2 flow, ensuring that the integration status is properly verified after authentication. It also enhances the reliability of the authentication process by adding better cleanup mechanisms and error handling.
=> feat: enhance OAuth2 integration

.changeset/fresh-cooks-punch.md, src/context/subi-connect.tsx, src/context/table/table-context.tsx, src/hooks/use-account-payroll.tsx, src/hooks/use-company.tsx, src/hooks/use-subi-connect-query.ts
This PR enhances the reliability and efficiency of query handling in the Subi Connect library by fixing dependency issues and standardizing query implementations.
The changes address several issues:
1. A duplicate dependency in SubiConnectProvider that could cause unnecessary re-renders
2. Inconsistent query implementation patterns across components
3. Suboptimal type handling in query options
4. Unnecessary async wrapper in useAccountPayrollSystem
=> refactor: optimize SubiConnect query implementations
